import Head from 'next/head'
import { Typography } from '@mui/material'

const Home = () => (
  <>
    <Head>
      <title>Quora</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Typography variant='h2' >Welcome</Typography>
  </>
)

export default Home
