import type { Metadata } from "next";
import Box from "@mui/material/Box";
import Drawer from "@mui/material/Drawer";
import SideBarMenu from "@/components/organisms/Menu";
import { DRAWER_WIDTH } from "@/utils/consts";

export const metadata: Metadata = {
	title: "Quora",
	description: "Generated by create next app",
};

export default function NavLayout({ children }: { children: React.ReactNode }) {
	return (
		<Box sx={{ display: "flex" }}>
			<Drawer
				sx={{
					width: DRAWER_WIDTH,
					flexShrink: 0,
					"& .MuiDrawer-paper": {
						width: DRAWER_WIDTH,
						boxSizing: "border-box",
					},
				}}
				variant="permanent"
				anchor="left"
			>
				<SideBarMenu />
			</Drawer>
			<Box
				component="main"
				sx={{
					p:3,
					marginLeft:"500px",
					height: "100vh",
					display: "flex",
					flexDirection: "column",
					justifyContent: "start",
					alignItems: "center",
				}}
			>
				{children}
			</Box>
		</Box>
	);
}
